import { test, expect } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import path from 'node:path'
const shots=path.resolve('../docs/screenshots')
mkdirSync(shots,{recursive:true})
const pages={overview:'Tender overview',market:'What’s moving freight costs?',benchmark:'Compare your freight bids',scorecard:'Which partners deliver?',allocation:'Plan your shipping volume',methodology:'The detail behind the decisions'}
for(const width of [1440,375])for(const [route,title] of Object.entries(pages))test(`${route} works at ${width}px`,async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.setViewportSize({width,height:width===375?812:1000})
  await page.goto(`/#${route}`)
  await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible()
  await expect(page.locator('.page-content')).toBeVisible()
  if(route==='methodology')await expect(page.locator('.document h1')).toBeVisible()
  await page.evaluate(()=>document.fonts.ready)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await page.screenshot({path:path.join(shots,`${route}-${width}.png`),fullPage:true})
})
test('benchmark filtering, calculations and export',async({page})=>{
  await page.goto('/#benchmark')
  await page.getByRole('textbox',{name:'Search lanes'}).fill('Hamburg')
  await expect(page.locator('.benchmark-table tbody tr')).toHaveCount(1)
  await page.locator('.bid-cell').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('Synthetic bid-median surcharge reference')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'CSV',exact:true}).click()
  expect((await download).suggestedFilename()).toBe('alpine-tender-synthetic.csv')
  await page.getByRole('textbox',{name:'Search lanes'}).fill('No such city')
  await expect(page.getByRole('heading',{name:'No matching lanes'})).toBeVisible()
})
test('allocation responds, explains infeasibility and resets',async({page})=>{
  await page.goto('/#allocation')
  await expect(page.locator('.allocation-result')).toBeVisible()
  const initial=await page.locator('.allocation-numbers').innerText()
  await page.getByLabel('Cost versus reliability').fill('100')
  await expect(page.locator('.allocation-numbers')).not.toHaveText(initial,{useInnerText:true})
  await page.getByLabel('Weekly volume',{exact:true}).fill('500')
  await expect(page.getByRole('heading',{name:'This allocation isn’t feasible'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Export allocation'})).toBeDisabled()
  await page.getByRole('button',{name:'Reset scenario'}).click()
  await expect(page.locator('.allocation-result')).toBeVisible()
})
test('weights update partner scores and theme persists',async({page})=>{
  await page.goto('/#scorecard')
  const initial=await page.locator('.score-ring').first().innerText()
  await page.getByLabel('Price competitiveness weight').fill('100')
  await expect(page.locator('.score-ring').first()).not.toHaveText(initial,{useInnerText:true})
  await page.getByRole('button',{name:'Reset default weights'}).click()
  await expect(page.locator('.score-ring').first()).toHaveText(initial,{useInnerText:true})
  await page.getByRole('button',{name:'Switch to dark theme'}).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.getByRole('button',{name:'Switch to light theme'}).click()
  await page.screenshot({path:path.join(shots,'scorecard-light.png'),fullPage:true})
})
test('market sources expose provenance and empty selection',async({page})=>{
  await page.goto('/#market')
  await page.locator('.source-line button').first().click()
  await expect(page.getByRole('dialog')).toContainText('Fetched (UTC)')
  await expect(page.getByRole('link',{name:'Open original source'})).toHaveAttribute('href',/energy.ec.europa.eu/)
  await page.getByRole('button',{name:'Close details'}).click()
  for(const name of ['Austria','Germany','Italy'])await page.getByRole('button',{name,exact:true}).click()
  await expect(page.getByText('Choose a country to show its trend.')).toBeVisible()
})
test('load failure offers recovery without invented numbers',async({page})=>{
  await page.route('**/data/diesel.json',route=>route.fulfill({status:503,body:'Unavailable'}))
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('The cockpit couldn’t load')
  await expect(page.locator('.kpi-value')).toHaveCount(0)
  await page.unroute('**/data/diesel.json')
  await page.getByRole('button',{name:'Try again'}).click()
  await expect(page.locator('.kpi-value').first()).toBeVisible()
})
test('mobile navigation and benchmark scroll remain usable',async({page})=>{
  await page.setViewportSize({width:375,height:812});await page.goto('/')
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('link',{name:'Tender Benchmark',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Compare your freight bids'})).toBeVisible()
  expect(await page.locator('.benchmark-scroll').evaluate(e=>e.scrollWidth>e.clientWidth)).toBe(true)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('skip navigation keeps the active page and focuses main content',async({page})=>{
  await page.goto('/#scorecard')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link',{name:'Skip to content'})).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
  await expect(page.getByRole('heading',{name:'Which partners deliver?'})).toBeVisible()
})
