import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BookOpen, ChartNoAxesCombined, ChevronRight, CircleHelp, LayoutDashboard, Menu, Moon, Mountain, Radio, RefreshCw, ShieldCheck, Sun, Truck, X } from 'lucide-react'
import { DEFAULT_WEIGHTS, scorePartners } from './lib/analytics'
import { formatDate, loadData } from './lib/data'
import type { AppData, Weights } from './lib/types'
import { DISCLAIMER, DetailDialog, Empty, type Detail } from './components/Common'
import { AllocationPage, BenchmarkPage, Market, Methodology, Overview, Scorecard, type Page } from './pages/Pages'

const pages = [
  {id:'overview',name:'Overview',icon:LayoutDashboard,title:'Tender overview',description:'Your European freight network. The costs, the partners and your next decision.'},
  {id:'market',name:'Market Pulse',icon:Radio,title:'What’s moving freight costs?',description:'Follow fuel prices and exchange rates before you negotiate your next tender.'},
  {id:'benchmark',name:'Tender Benchmark',icon:ChartNoAxesCombined,title:'Compare your freight bids',description:'See which prices deserve a closer look — and understand exactly why.'},
  {id:'scorecard',name:'3PL Scorecard',icon:ShieldCheck,title:'Which partners deliver?',description:'Compare service and cost. Choose the partners you can rely on.'},
  {id:'allocation',name:'Volume Allocation',icon:Truck,title:'Plan your shipping volume',description:'Choose a route, set your priorities and find the right partner mix.'},
  {id:'methodology',name:'Methodology',icon:BookOpen,title:'The detail behind the decisions',description:'A transparent guide to the sources, assumptions and calculations.'},
] as const
const getPage=():Page=>pages.some(p=>p.id===location.hash.slice(1))?location.hash.slice(1) as Page:'overview'
export default function App(){
  const [page,setPage]=useState<Page>(getPage),[data,setData]=useState<AppData|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0)
  const [weights,setWeights]=useState<Weights>(DEFAULT_WEIGHTS),[selectedLane,setSelectedLane]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[mobile,setMobile]=useState(false)
  const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('alpine-theme-v2')==='dark'?'dark':'light'}catch{return 'light'}})
  useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('alpine-theme-v2',theme)}catch{/* Private browsing can disable storage. */}},[theme])
  useEffect(()=>{const handler=()=>{setPage(getPage());setMobile(false)};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler)},[])
  useEffect(()=>{const controller=new AbortController();setError('');loadData(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[attempt])
  const scores=useMemo(()=>data?scorePartners(data.partners.records,data.bids.records,data.performance.records,weights):[],[data,weights])
  function navigate(next:Page,lane?:string){if(lane)setSelectedLane(lane);setPage(next);location.hash=next;setMobile(false);setDetail(null);window.scrollTo({top:0,behavior:'instant'})}
  const current=pages.find(p=>p.id===page)!
  const View={overview:Overview,market:Market,benchmark:BenchmarkPage,scorecard:Scorecard,allocation:AllocationPage,methodology:Methodology}[page]
  return <><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById("main")?.focus()}}>Skip to content</a>{mobile&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
  <aside className={`sidebar ${mobile?'open':''}`}><a href="#overview" className="brand" onClick={()=>navigate('overview')}>{data?.brand.logo?<img src={data.brand.logo} alt="Red Bull" className="official-logo"/>:<Mountain size={36} strokeWidth={1.5}/>}<span>Alpine Freight Cockpit<strong>GLOBAL LOGISTICS · PORTFOLIO</strong></span></a><div className="sidebar-rule"/><span className="nav-label">TENDER WORKSPACE</span><nav aria-label="Main navigation">{pages.slice(0,5).map(p=><a href={`#${p.id}`} key={p.id} className={page===p.id?'active':''} aria-current={page===p.id?'page':undefined} onClick={e=>{e.preventDefault();navigate(p.id)}}><p.icon size={18}/><span>{p.name}</span>{page===p.id&&<ChevronRight size={14}/>}</a>)}</nav><div className="sidebar-bottom"><div className="network-card"><span className="live-dot"/>EUROPEAN ROAD NETWORK<strong>Salzburg → Europe</strong><span>Salzburg, Austria <ArrowUpRight size={13}/></span></div><a href="#methodology" className={`method-link ${page==='methodology'?'active':''}`} onClick={e=>{e.preventDefault();navigate('methodology')}}><BookOpen size={17}/>Methodology<ArrowUpRight size={13}/></a><div className="profile"><span>KA</span><div>Mohammed Kaif Ahmed<small>Independent portfolio project</small></div></div></div></aside>
  <div className="app-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button menu-button" aria-label={mobile?'Close navigation':'Open navigation'} onClick={()=>setMobile(!mobile)}>{mobile?<X size={20}/>:<Menu size={20}/>}</button><img className="mobile-brand" src="/brand/redbull-logo.svg" alt="Red Bull"/><span>Global logistics</span><ChevronRight size={13}/><strong>{current.name}</strong></div><div className="header-actions"><span className="demo-pill"><span/>PORTFOLIO DEMO</span><button className="icon-button" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button help-button" aria-label="Open methodology" onClick={()=>navigate('methodology')}><CircleHelp size={18}/></button></div></header>
  <main id="main" tabIndex={-1}><div className="page-heading"><svg className="contours" viewBox="0 0 520 160" aria-hidden="true"><g fill="none" stroke="currentColor">{Array.from({length:9},(_,i)=><path key={i} d={`M${80+i*17},180 C${-40+i*22},80 ${180+i*15},-55 ${265+i*18},45 S${390+i*21},155 ${510+i*17},-30`}/>)}</g></svg><div className="heading-eyebrow"><span className="yellow-rule"/>EUROPEAN ROAD FREIGHT</div><div className="heading-row"><div><h1>{current.title}</h1><p>{current.description}</p></div><div className="snapshot-label"><span className="live-dot"/><div>MARKET DATA UPDATED<small>{data?`Fetched ${formatDate(data.fx.meta.fetched_at)}`:'Connecting to data…'}</small></div></div></div>{page==='overview'&&<p className="intro-disclaimer">{DISCLAIMER}</p>}</div>
  {error?<div role="alert"><Empty title="The cockpit couldn’t load">{error}</Empty><button className="button primary" onClick={()=>setAttempt(a=>a+1)}><RefreshCw size={15}/>Try again</button></div>:data?<div className="page-content" key={page}><View data={data} scores={scores} weights={weights} setWeights={setWeights} setDetail={setDetail} navigate={navigate} selectedLane={selectedLane} setSelectedLane={setSelectedLane}/></div>:<div aria-busy="true" aria-label="Loading cockpit"><div className="kpi-grid">{[0,1,2,3].map(i=><div key={i} className="skeleton" style={{height:145}}/>)}</div><div className="skeleton" style={{height:480,marginTop:24}}/></div>}
  <footer><div><img className="footer-brand" src="/brand/redbull-logo.svg" alt="Red Bull"/><strong>ALPINE FREIGHT COCKPIT</strong><span>From insight to impact.</span></div><p>{DISCLAIMER}</p><button className="text-button" onClick={()=>navigate('methodology')}>Sources & methodology<ArrowUpRight size={13}/></button></footer></main></div><DetailDialog detail={detail} close={()=>setDetail(null)}/></>
}
