import { useId } from 'react'
import { number } from '../lib/data'
export interface Series {name:string;colour:string;values:number[]}
export function LineChart({series,labels,unit,ariaLabel}:{series:Series[];labels:string[];unit:string;ariaLabel:string}) {
  const id=useId().replace(/:/g,'')
  if(!series.length||!labels.length)return <div className="empty">Choose a country to show its trend.</div>
  const all=series.flatMap(s=>s.values).filter(Number.isFinite), min=Math.min(...all)*.95, max=Math.max(...all)*1.04
  if(!all.length)return <div className="empty">No observations available for this selection.</div>
  const x=(i:number)=>54+i/(labels.length-1||1)*630, y=(v:number)=>210-(v-min)/(max-min||1)*170
  return <div className="chart-wrap"><svg viewBox="0 0 720 258" role="img" aria-label={ariaLabel}><title>{ariaLabel}</title><desc>{series.map(s=>`${s.name}: first ${number(s.values[0],3)}, latest ${number(s.values.at(-1)??0,3)} ${unit}`).join('. ')}</desc><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={series[0].colour} stopOpacity=".16"/><stop offset="1" stopColor={series[0].colour} stopOpacity="0"/></linearGradient></defs>{Array.from({length:5},(_,i)=>{const v=min+(max-min)*i/4;return <g key={i}><line x1="54" x2="690" y1={y(v)} y2={y(v)} className="chart-grid"/><text x="43" y={y(v)+4} textAnchor="end" className="axis">{number(v,unit==='EUR/L'?2:0)}</text></g>})}{series.map((s,k)=>{const path=s.values.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join(' ');return <g key={s.name}>{k===0&&<path d={`${path} L${x(s.values.length-1)},220 L54,220Z`} fill={`url(#${id})`}/>}<path d={path} fill="none" stroke={s.colour} strokeWidth="2.5" strokeLinejoin="round"/><circle cx={x(s.values.length-1)} cy={y(s.values.at(-1)!)} r="4" fill={s.colour}/></g>})}{labels.filter((_,i)=>i===0||i===labels.length-1||i%Math.max(1,Math.floor(labels.length/4))===0).map(label=>{const i=labels.indexOf(label);return <text key={label} x={x(i)} y="247" textAnchor="middle" className="axis">{new Date(label).toLocaleDateString('en-GB',{month:'short',...(unit==='Index'?{year:'2-digit' as const}:{day:'numeric' as const}),timeZone:'UTC'})}</text>})}<text x="54" y="17" className="axis">{unit}</text></svg><div className="chart-key">{series.map(s=><span key={s.name}><i style={{background:s.colour}}/>{s.name}<strong>{number(s.values.at(-1)!,unit==='EUR/L'?3:1)}</strong></span>)}</div></div>
}
